### ISSUE TITLE
“add user” , new required fields.

### ISSUE THREAD

**Issue by turukawa** [whythawk/hrd#103]
For “add user” , “name” and “position” should be added to the required details.

**Comment by tobes** [comment]
@ratkins5 
These are new fields where do we want them displayed?

I assume the user can edit these themselves too is this correct?

**Comment by ratkins5** [comment]
Yes, whoever has the user edit rights can edit these fields.  I'd suggest putting these boxes between the "organisation' and 'permission' sections, but as you see best really.

**Comment by ratkins5** [comment]
@tobes Yes, whoever has the user edit rights can edit these fields. I'd suggest putting these boxes between the "organisation' and 'permission' sections, but as you see best really.

**Comment by tobes** [comment]
added and live

**Comment by ratkins5** [comment]
Thanks Toby.
