### ISSUE TITLE
User reported 'Server Error' when trying to access message board

### ISSUE THREAD

**Issue by ratkins5** [whythawk/hrd#105]
@tobes 

User mariairaizoz reports this, from 28/7/15, using Chrome (on Windows I think).  I can't replicate this on Chrome (Version 44.0.2403.125 (64-bit)) on my mac.  Any suggestions?

Richard

**Comment by tobes** [comment]
I've found the problem (log files are wonderful things)

I'll try to get it and also the news stuff up tonight (sorry for the delay on that)

**Comment by tobes** [comment]
I decided just to do the updates now.  If this issue is now resolved then close it, cheers

**Comment by ratkins5** [comment]
Hi Toby, they tell me it's working for them now - thank you!

Richard
