### ISSUE TITLE
Discrepancy between French and other languages in display of member org database entry

### ISSUE THREAD

**Issue by ratkins5** [whythawk/hrd#107]
On the member org page for Front Line Defenders, under 'Duration of Relocation', 3 months has been ticked.  In French it displays as '3-6 months'.  The other languages display correctly.  

See https://hrdrelocation.eu/fr/admin/org_edit/9992257c-2491-4d99-9acd-08c4bd4fa5da for the data entry, https://hrdrelocation.eu/fr/org/9992257c-2491-4d99-9acd-08c4bd4fa5da for the displayed page.

**Comment by tobes** [comment]
The translations were just wrong ie switched around

I have just swapped them as it was easier than getting you to have to do it.

in future just look at the code translations https://hrdrelocation.eu/fr/admin/category/org?lang=en to see if they are correct there

**Comment by ratkins5** [comment]
Sorry, I should have figured that out.  Looking at these I notice that they aren't in duration order which may have muddled it, but it probably doesn't matter in practice and I'm not going to fiddle for fear of messing up the Arabic and Russian wot I don't understand...  Thanks for fixing it.
