### ISSUE TITLE
Request to change the display of countries to 'All', when all are selected

### ISSUE THREAD

**Issue by ratkins5** [whythawk/hrd#108]
Request that where member organisations have ticked all countries, that we simply display 'all' instead of listing them all (which looks huge).  Is this trivial or difficult to do?

**Comment by tobes** [comment]
This shouldn't be too difficult.  I'd suggest it would take half a day to - code, test, update etc

**Comment by tobes** [comment]
live now

**Comment by ratkins5** [comment]
Thanks Toby.  Looking at the page entries, almost all of them at the moment have no countries ticked.  I thought I remembered that most of them had ticked everything.  Has something been reset with this change?

**Comment by tobes** [comment]
No but they may have done it for some reason

**Comment by ratkins5** [comment]
Is this working?  Front Line Defenders still displays the long list of countries instead of saying 'All'.

**Comment by tobes** [comment]
I think I added the wrong category, now fixed - sorry was without pc till now
