### ISSUE TITLE
Client request for daily email digest to be sent to all users.

### ISSUE THREAD

**Issue by ratkins5** [whythawk/hrd#110]
Daily email digest to all users which informs them:

1) The names of any and all new topics created since the last email was sent.
2) The  names of those topics which have received new posts since the last email, plus the number (but not any content of) of new posts in each of those topics.

**Comment by ratkins5** [comment]
Additional info:
- Ability for recipients to opt out if they wish.
- Request that no email is sent that day if there is no new topics or posts new since the last email was sent out.

**Comment by tobes** [comment]
send at midnight

**Comment by tobes** [comment]
live but in testing mode

**Comment by tobes** [comment]
New topic:

email to all
'a new topic has been created'  + info

if tracking topic that has reply:

'the following topic you are tracking, has a reply'

**Comment by tobes** [comment]
Ok, I've updated this.

It is hard to test this functionality on the live site but locally it works as wanted.  And the testing I have done on the live site suggests it is working there too.

**Comment by ratkins5** [comment]
Hi Toby, is the digest switched on?  I've seen there was a new topic posted 3 days ago ("Fully Funded PhD at Portsmouth"), but I've not had any emails at all in the last 3-4 days.  Thanks, Richard

**Comment by tobes** [comment]
On 7 December 2015 at 11:53, Richard Atkinson <notifications@github.com>
wrote:

> Hi Toby, is the digest switched on? I've seen there was a new topic posted
> 3 days ago ("Fully Funded PhD at Portsmouth"), but I've not had any emails
> at all in the last 3-4 days. Thanks, Richard
>
>
yeah I saw that too I'm going to get that fixed then turn it on.  Should
start from tomorrow.

Sorry I've been distracted by the smart streets stuff, and was in a meeting
this morning.  I'll find some time this afternoon to look at hrd

Toby

**Comment by ratkins5** [comment]
Hi Toby, 

I know you've been maxed on Smart Streets, but can you tell me if it's switched on for everyone?  I thought it was but I'm hearing it's not.  Thanks, Richard

**Comment by tobes** [comment]
It might be that the email was marked as spam (mine where initially) It's turned on for everyone and lot's of emails were sent on the 1st of Jan.

Let me know if others should have been sent

**Comment by turukawa** [comment]
@tobes can you check the logs? Confirmation from the client that these are still not going through. If it's a matter of our email being blocked by servers, we may need to continue a specialist bulk mail service.

**Comment by tobes** [comment]
just tell me who didn't get it that was expecting it

just one name would do

I need information not a vague rumour
