### ISSUE TITLE
Unable to enter details for new member organisation, Pen International

### ISSUE THREAD

**Issue by ratkins5** [whythawk/hrd#111]
Client reports unable to enter Spanish details for Pen International (other organisations are OK).

https://hrdrelocation.eu/en/admin/org_edit/0efce55a-b9cc-482c-9e58-2e4df09ea267

**Comment by tobes** [comment]
Hmmm,

looking at the logs it looks like they had an issue with the pgp key being too long but that is in the english content not spanish.

If you could email me the spanish translation I can have a better look but I can't see an issue in the logs.

**Comment by ratkins5** [comment]
OK, client clarifies that actually they have trouble with PEN for all languages.  Have asked them to confirm the PGP key.

**Comment by tobes** [comment]
This seems to be translated now so closing
