### ISSUE TITLE
Black/white speech bubble for read/unread items seems not to work?

### ISSUE THREAD

**Issue by ratkins5** [whythawk/hrd#115]
Some Sections show a black speech bubble (which I believe means there is new stuff in that section that I haven't read), but if I go in to that section and open every item, when I return and refresh the page the black speech bubble stays black.

Similarly, the speech bubbles for Topics within each Section seem always to be white, even for ones I haven't yet read - is the intent the same at both levels of the hierarchy?

**Comment by tobes** [comment]
This should now be working as expected
