### ISSUE TITLE
Menu items become issue on small screen

### ISSUE THREAD

**Issue by tobes** [whythawk/hrd#116]

**Comment by tobes** [comment]
Ok this is going to need someone like Rory to look into this.

I've had a look but ultimately the menu needs a redesign,  the essential problem is having to much stuff in the menu but I think we are stuck with that.

**Comment by turukawa** [comment]
There is a specific size point when the menu itself fails (i.e. it isn't just a design mess, the menu items themselves become inactive). @tobes @rrymrrsn

**Comment by turukawa** [comment]
Merging into [Issue 122](https://github.com/whythawk/hrd/issues/122)
