### ISSUE TITLE
@tobes @turukawa Change to bootstrap responsive class in header

### ISSUE THREAD

**Issue by rrymrrsn** [whythawk/hrd#122]
The col-xs classes for **.hrd_logo** and **.sitetitle** would respond better if changed to **col-xs-12**. This will be backed up by some CSS changes coming shortly.

```<div class="header container red-left-border">
    <div class="row">
        <div class="hrd_logo col-xs-12 col-sm-3 col-md-2">
            <a href="https://hrdrelocation.eu/en/"><img width="auto" height="130" src="./EU Human Rights Defenders_files/hrd_logo_163x130_Alt_RedBlue.png" alt=""></a>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6">
            <h3 class="sitetitle">EU Human Rights Defenders Relocation Platform<br>  
            </h3>
        </div>  
        <div class="eu_logo hidden-xs col-sm-3 col-md-3 pull-right">
            <a href="https://hrdrelocation.eu/en/get_involved#"><img width="auto" height="130" src="./EU Human Rights Defenders_files/EC_logo_173x130.jpg" alt=""></a>
        </div>
    </div>`

**Comment by turukawa** [comment]
@rrymrrsn Rory, can you follow up on this please ...

**Comment by rrymrrsn** [comment]
@turukawa Removing the two search menu items and replacing with Search at the top level and then Resources and Members at the second level seems to do the trick. Let me know when you've had a look at the test below.
https://dl.dropboxusercontent.com/u/18971970/Whythawk/HRD/EUHRD_MenuIssue.html

**Comment by tobes** [comment]
That doesn't work due to them being able to add remove menu items.

In my opinion just changing the menu to being an old school drop down thing rather than having 2 rows would be a better fix.

**Comment by turukawa** [comment]
Yeah, it still breaks at the second break-point. It's odd, though, because the submenu for Search is just fine (it is open in the list menu view), but for Admin is locked closed.

**Comment by rrymrrsn** [comment]
@turukawa The Admin menu staying closed may be to do with the way I set up the test. Must be something missing. Just to clarify is this the only break you are talking about or have you seen something else?

**Comment by turukawa** [comment]
At this stage - in the demo you've set up - that is the break-point where it fails.

**Comment by rrymrrsn** [comment]
I'm afraid i don't have time before I go away to redesign the menu. It will have my full attention again when I return on 27 Feb. Have suggested some changes which may work in the meantime.
