### ISSUE TITLE
Arabic translation right-to-left

### ISSUE THREAD

**Issue by ratkins5** [whythawk/hrd#76]
@tobes Request from the arabic translator, "Arabic writing goes from right to left. Could this be arranged on the website".

**Comment by tobes** [comment]
could you be a bit more specific where this is a problem.
Is it when the translations are entered? Is it all translations just certain ones?

**Comment by ratkins5** [comment]
@ I'll have to ask that.  I believe it's when they attempt to write text in the arabic space.  Obviously, this is a characteristic that's unique to/ only required for the arabic material.

**Comment by tobes** [comment]
ok, can you find out if some work.  I'm sure I did stuff around this eg the content editor in the pages part of the cms

**Comment by ratkins5** [comment]
Will do.  To be honest I was surprised by the request as I knew you knew of the need.

**Comment by ratkins5** [comment]
@tobes I've just tried to enter text to translate the homepage blurb, and one of the category titles, into arabic.  As you type the text progresses out from the left towards the right; they'd like it to progress out from the right towards the left.

**Comment by tobes** [comment]
Ok,  this fix should now be live.

Can you get them to test as I don't have a arabic keyboard and that is needed to enter the text correctly english is still ltr but right aligned.

**Comment by ratkins5** [comment]
Yep, looks good to me.  Thanks for getting to that so quickly.
