### ISSUE TITLE
Translators user management

### ISSUE THREAD

**Issue by tobes** [whythawk/hrd#77]
@ratkins5 

You said that they want translators to not need to be `sys admins`.  Do you think that just `content editor` is enough, ie can add and translate content but not user management etc.

**Comment by ratkins5** [comment]
@tobes The ideal is that translators have a lower level than the current content editing level.  Definitely we don't want translators having any user management rights.  Ideally, they'd only have the ability to edit the translation page of their own specified language.  That is, they can't edit the English version and preferably also can't edit they other languages.  Thus, you'd give them french tranlsation rights and they'd not be able to edit the English master, nor the Spanish etc.  Give me a call if further explanation would help.
