### ISSUE TITLE
Some translated pages not authorised (returning 403)

### ISSUE THREAD

**Issue by ratkins5** [whythawk/hrd#79]
When not logged in, some pages (esp. in translated languages) return 403 - not authorised.  Pages affected include:

English - About Us.
French - About Us, About HRDs.
Spanish - Home, About Us, About HRDs
Russian - Home, About Us, About HRDs

**Comment by tobes** [comment]
If you're not logged in you are not authorised what is the issue?

**Comment by ratkins5** [comment]
Issue is that these are pages that are public view - they're the ones that are supposed to be readable by the world.

**Comment by tobes** [comment]
can you give me specific urls that cause the problem.

Also are people fucking with them?   about is not active I get a 404 error

**Comment by ratkins5** [comment]
OK, I'll go through them and check it's not 'Active' being set wrong.  Got a call to do now, I'll cancel or ad URL info to this issue accordingly when I've done those checks.

**Comment by tobes** [comment]
I think it all works and just someone set them to private

**Comment by ratkins5** [comment]
Just checking this this morning (using Maria's login as mine not working), when logged in it's all visible, when not logged in some pages (e.g. the tab for 'About HRDs' in French) returns 403.  'Active' and 'Private' can only be set on the English page - the other languages ought at least to behave the same as English (i.e. language shouldn't affect the display criteria)?

**Comment by ratkins5** [comment]
URL for the above https://hrdrelocation.eu/fr/hrds

**Comment by tobes** [comment]
ok, not sure quite how this happened but re-saving the english version fixed the issue.

**Comment by ratkins5** [comment]
OK, thanks for chasing that one down, that's great.

**Comment by ratkins5** [comment]
Still seeing the same thing on the arabic homepage though https://hrdrelocation.eu/ar/
Also the Spanish homepage https://hrdrelocation.eu/es/
Which is weird.  Did you re-save the whole site or just that affected page?

**Comment by tobes** [comment]
just the /hrd page

I've now saved them all.  Must be some weird issue I'll investigate

**Comment by tobes** [comment]
was about null codes - fixed
