### ISSUE TITLE
Change forum to section

### ISSUE THREAD

**Issue by tobes** [whythawk/hrd#81]

**Comment by ratkins5** [comment]
Similarly requested from client, to harmonise terms 'message board' and 'forum', preferably changing the word forum to message board.  Thus the hierarchy reads:
Message board/ Section/ Topic/ Post.

**Comment by tobes** [comment]
Ok,  I've made changes and updated the site

I may have missed some of these so let me know if there are errors/omissions and the url where they show

**Comment by ratkins5** [comment]
Can't find any.  Thanks for doing that, makes a surprising difference to using it.
