### ISSUE TITLE
Message board 'Report' function on message board returns Error 502

### ISSUE THREAD

**Issue by ratkins5** [whythawk/hrd#84]
Tried our Report (i.e. flag for moderation) function, returns 502 as per image here.
![screen shot 2015-02-11 at 10 27 32](https://cloud.githubusercontent.com/assets/9843434/6145350/caadaa94-b1d8-11e4-8d88-fc230fd9c9c3.png)

**Comment by tobes** [comment]
please give a url for this problem so I can replicate it

**Comment by ratkins5** [comment]
https://hrdrelocation.eu/en/forum/topic/4-richard-s-shiny-new-topic-thursday-morning?page=1#pid11

Just hit 'Report' on the comment, type anything in the dialogue box and submit, should replicate it.

It doesn't do this on all comments - I tried it on 'Test topic' (the line above) and it reported fine.

**Comment by tobes** [comment]
works for me

**Comment by tobes** [comment]
ok found the problem also fixes issue #85
