### ISSUE TITLE
Message board reported issues showing wrong attribution

### ISSUE THREAD

**Issue by ratkins5** [whythawk/hrd#85]
Raised (dummy) reports on message board, logged in as ratkins, but in the panel showing reports these are attributed to a different person (Eevdokimova)

https://hrdrelocation.eu/en/forum/admin/reports/unread

**Comment by tobes** [comment]
please could you edit this so I can understand what the issue is

**Comment by ratkins5** [comment]
The problem is that it gives Eevdokimova as the person who filed the 'report'.  But it wasn't Eevdokimova who reported, it was ratkins.

**Comment by tobes** [comment]
fixed
