### ISSUE TITLE
Use of return key on login and verification dialogue boxes

### ISSUE THREAD

**Issue by ratkins5** [whythawk/hrd#87]
Pressing return key at the username/password stage of login is accepted (i.e. works the same as clicking the 'login' button).  At the next dialog box pressing return acts as a cancel command and 'Continue' must be click.  Would it be clearer to users if pressing return were rejected (or accepted) in both places?

**Comment by tobes** [comment]
i've fixed this already but not pushed live

**Comment by ratkins5** [comment]
OK cool

**Comment by tobes** [comment]
yes
