### ISSUE TITLE
email text 

### ISSUE THREAD

**Issue by tobes** [whythawk/hrd#88]
HRD password reset request
'A password reset has been requested please click on the link or paste it into your browser.  this link is valid for 24 hours.'

HRD access
'You have been envited to join the Human Rights Defenders.'

**Comment by turukawa** [comment]
Spelling / Punctuation corrections:

HRD password reset request
'A password reset has been requested. Please click on the link below or paste it into your browser. This link is valid for 24 hours.'

HRD access
'You have been invited to join HRDRelocation.eu.'

**Comment by tobes** [comment]
updated
