### ISSUE TITLE
Attempt to delete a message board category returns 502 error

### ISSUE THREAD

**Issue by ratkins5** [whythawk/hrd#89]
Attempting to delete the 'Welcome' category on the message board returns Error 502.

URL: https://hrdrelocation.eu/en/forum/admin/forums/1/delete
![screen shot 2015-02-23 at 11 02 44](https://cloud.githubusercontent.com/assets/9843434/6326622/8e1649fc-bb4b-11e4-9c06-3fc282e6203c.png)

**Comment by tobes** [comment]
This should be fixed now too but please test

again this was about a reported post somewhere in the category

**Comment by ratkins5** [comment]
Tested this several times and not found any errors; thank you.
