### ISSUE TITLE
Message board down?

### ISSUE THREAD

**Issue by ratkins5** [whythawk/hrd#92]
Logged in as RAtestuser (a no-powers basic user I created for test purposes), unable to access the message board.  https://hrdrelocation.eu/en/forum
![screen shot 2015-02-25 at 09 54 19](https://cloud.githubusercontent.com/assets/9843434/6368421/75fba79c-bcd4-11e4-81a1-7d7414605094.png)

I can, however, access the message board normally when logged in as ratkins, my normal username which has admin rights.

**Comment by tobes** [comment]
What has been done recently on the message board?  This is a much wider issue I fear

**Comment by ratkins5** [comment]
Deleted some topics, added some new stuff.  A fair bit of activity but nothing that ought to break it.  What wider issue do you think might be happening?

**Comment by tobes** [comment]
ok fixed that problem

**Comment by ratkins5** [comment]
No wider issue - alarm over?

**Comment by tobes** [comment]
yeah it is around unread posts so less of an issue just a pain
