### ISSUE TITLE
Login attempt returns 502 error

### ISSUE THREAD

**Issue by ratkins5** [whythawk/hrd#93]
Site appears to be up, you can click login and it gives you the dialogue box, but having entered name and password it returns a 502 error.
![screen shot 2015-03-03 at 08 21 31](https://cloud.githubusercontent.com/assets/9843434/6458732/d6927ae6-c17e-11e4-908d-51a6c252386f.png)

Sorry, no url as I deleted the original page and then couldn't replicate as the site was down.

**Comment by tobes** [comment]
@ratkins5 if you don't allocate these to me or add @tobes in a comment I can't see them - closing as this was related to an error that was fixed.

**Comment by ratkins5** [comment]
Hi Toby,  my error, I forgot to allocate it - sorry!  Richard
