### ISSUE TITLE
Gulf Centre for Human Rights duplicate weirdness

### ISSUE THREAD

**Issue by ratkins5** [whythawk/hrd#94]
Gulf Centre for Human Rights organisation's page looks like it has some kind of glitch.  When searching orgs two entries are returned, one with all the address and 'tick' data, the other without.  But in the editor only one entry can be seen (which is the entry without the data).

See (version with data): https://hrdrelocation.eu/en/org/afc45738-8528-4d5d-aa44-7eeec6d93543

See (version missing data): https://hrdrelocation.eu/en/org/71d0d3c2-b076-43dc-9b70-dcd4840dc486

See (single) entry in database: https://hrdrelocation.eu/en/admin/org_edit/71d0d3c2-b076-43dc-9b70-dcd4840dc486

**Comment by tobes** [comment]
Not quite sure how that happened but I've fixed all the data
