### ISSUE TITLE
Message Board - notifications of new posts in topics they follow

### ISSUE THREAD

**Issue by turukawa** [whythawk/hrd#98]
Some users, when following a topic, don't see any notifications (or counts) of new items in the topics they follow when they login. One user does, and there doesn't appear to be any difference between them.

Selecting or deselecting the "track" option appears to have no affect and users are unclear what it is for, and whether it is supposed to have any bearing on following a topic.

I have no access to the board, so this is client-reported.

**Comment by tobes** [comment]
@ratkins5 

part of the message issue is about a 'cut off' this is where posts are not shown as new after a certain date.  by default this is 7 days but given the level of use I think we should change this to 30 days what is your thought?

**Comment by ratkins5** [comment]
@tobes 
Yes, moving the cutoff date as you suggest seems sensible.  That said, I had assumed that posts were 'new' to a user until they had seen them, so that newness depends on user actions rather than the age of the post - is this not how it works?

**Comment by tobes** [comment]
it sort of decides posts are no longer new after a certain point, this is probably good for a high turnover forum but not so relevant for us.  I think the 30 day cut off and posts before you joined makes sense to me.  or we could just use cut off or joined date logic.

**Comment by ratkins5** [comment]
30 days and before you joined (otherwise newbie get a wall of newness?) seems sensible to me.

**Comment by tobes** [comment]
now live
